version: '3'

services:
  web:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8000:8000"
    volumes:
      - ./src/:/code
    tty: true

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 3308:3308
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
